### ISSUE TITLE
BokehUserWarning if plotting both original and resampled data

### ISSUE THREAD

**Issue by 0liu** [verybadsoldier/backtrader_plotting#36]
If adding both a set of data and its resample version to Backtrader Cerebro, plotting seems cannot handle them because of their different lengths. Bokeh warns ColumnDataSource's columns are not same length, and eventually raises OverflowError. The error output below is after running a simple backtest with 1-minute bars and resampled 5-minute bars. Obviously the issue has nothing to do with the strategy itself.

Error output:

```
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('4618412688close', 7336), ('4618412688colors_bars', 7336), ('4618412688colors_outline', 7336), ('4618412688colors_wicks', 7336), ('4618412688high', 7336), ('4618412688low', 7336), ('4618412688open', 7336), ('4618412688volume', 7336), ('4618412688volume_colors', 7336), ('4627372112', 7335), ('datetime', 7336), ('index', 7336)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('4618412688close', 7336), ('4618412688colors_bars', 7336), ('4618412688colors_outline', 7336), ('4618412688colors_wicks', 7336), ('4618412688high', 7336), ('4618412688low', 7336), ('4618412688open', 7336), ('4618412688volume', 7336), ('4618412688volume_colors', 7336), ('4627372112', 7335), ('4627372304', 7335), ('datetime', 7336), ('index', 7336)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('4618412688close', 7336), ('4618412688colors_bars', 7336), ('4618412688colors_outline', 7336), ('4618412688colors_wicks', 7336), ('4618412688high', 7336), ('4618412688low', 7336), ('4618412688open', 7336), ('4618412688volume', 7336), ('4618412688volume_colors', 7336), ('4627372112', 7335), ('4627372304', 7335), ('4627436816open', 7336), ('datetime', 7336), ('index', 7336)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('4618412688close', 7336), ('4618412688colors_bars', 7336), ('4618412688colors_outline', 7336), ('4618412688colors_wicks', 7336), ('4618412688high', 7336), ('4618412688low', 7336), ('4618412688open', 7336), ('4618412688volume', 7336), ('4618412688volume_colors', 7336), ('4627372112', 7335), ('4627372304', 7335), ('4627436816high', 7336), ('4627436816open', 7336), ('datetime', 7336), ('index', 7336)

....

Traceback (most recent call last):
  File "plot_example.py", line 36, in <module>
    cerebro.plot(b)
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader/cerebro.py", line 996, in plot
    plotter.show()
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 461, in show
    model = self.generate_model(idx)
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 314, in generate_model
    meta = Div(text=metadata.get_metadata_div(figurepage.strategy))
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 91, in get_metadata_div
    md += _get_datas(strategy)
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 39, in _get_datas
    'Time From:': bt.num2date(data.fromdate),
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader/utils/dateintern.py", line 165, in num2date
    ix = int(x)
OverflowError: cannot convert float infinity to integer
```

* Versions
    * backtrader_plotting commit: c1e3205ac0bc75d0a7ee6eae854194c49bb2e22b
    * Python: 3.7.6 in Conda environment
    * Bokeh: 1.4.0 installed by Conda

* Example for duplicating bug:

    * Data file: [NQ.csv.zip](https://github.com/verybadsoldier/backtrader_plotting/files/4179612/NQ.csv.zip)

    * Code:
```python
import datetime
import pandas as pd
import backtrader as bt
from backtrader_plotting import Bokeh
from backtrader_plotting.schemes import Tradimo


class MyStrategy(bt.Strategy):
    def next(self):
        pos = len(self.data)
        if pos == 45 or pos == 145:
            self.buy(self.datas[0], size=None)

        if pos == 116 or pos == 215:
            self.sell(self.datas[0], size=None)


if __name__ == '__main__':
    cerebro = bt.Cerebro()

    cerebro.addstrategy(MyStrategy)

    df = pd.read_csv("~/Workspace/NQ.csv", index_col=0)
    df.index = pd.DatetimeIndex(df.index)
    data =  bt.feeds.PandasData(dataname=df, name='NQ', timeframe=bt.TimeFrame.Minutes)
    cerebro.adddata(data)
    cerebro.resampledata(data, name='NQ_5min', timeframe=bt.TimeFrame.Minutes, compression=5)
    cerebro.addanalyzer(bt.analyzers.SharpeRatio)
    cerebro.run()

    b = Bokeh(filename='chart.html',style='bar', plot_mode="single", scheme=Tradimo())
    cerebro.plot(b)
```

**Comment by jesseliu0** [comment]
The OverflowError should be a different error. If removing the resampled data, the BokehUserWarning is gone but OverflowError is still raised.

**Comment by verybadsoldier** [comment]
Thanks for the report, it is really helpful. Will be fixed in the next update.

**Comment by verybadsoldier** [comment]
Should be both fixed now. Please try latest `develop` branch.

**Comment by 0liu** [comment]
Thank you so much for the update!

After installing commit 5df383d0e8a12910bdd6cb406ad7bfe0f2e084ab from develop branch, running the simple case above still throws some error:
```python
Traceback (most recent call last):
  File "testplot.py", line 32, in <module>
    cerebro.plot(b)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader/cerebro.py", line 991, in plot
    start=start, end=end, use=use)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 479, in plot
    df: pd.DataFrame = self.build_strategy_data(obj, start, end)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 450, in build_strategy_data
    dataline = convert_by_line_clock(dataline, line_clk, strat_clk)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/utils.py", line 65, in convert_by_line_clock
    new_line.append(line[i])
IndexError: array index out of range
```

I tried another more complex strategy, which throws different error below. Not sure how to debug it. Do you have any suggestion? Thanks.
```python
Traceback (most recent call last):
  File "trend_backtest_eod_mix.py", line 1259, in <module>
    result, analyzers = run_backtest(**test_args)
  File "trend_backtest_eod_mix.py", line 1224, in run_backtest
    cerebro.plot(bok, show=False)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader/cerebro.py", line 996, in plot
    plotter.show()
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 495, in show
    model = self.generate_model(idx)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 296, in generate_model
    meta = Div(text=metadata.get_metadata_div(figurepage.strategy))
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 96, in get_metadata_div
    md += _get_strategy(strategy)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 60, in _get_strategy
    md += _get_parameter_table(strategy.params)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 18, in _get_parameter_table
    params[k] = paramval2str(k, v)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/utils.py", line 29, in paramval2str
    return f"{value:.2f}"
TypeError: unsupported format string passed to tuple.__format__
```

**Comment by verybadsoldier** [comment]
The first problem was introduced by me by refactoring code, sorry. The second problem relates to tuple parameters not being supported but I added them.

Please try this this revision:
https://github.com/verybadsoldier/backtrader_plotting/commit/6d93db0a6e2b651e10f6b718c2ce9e029d71ca3a

**Comment by 0liu** [comment]
The first problem is solved and the simple test case can be plotted well. Awesome!
The second problem relates to parameter types, because the strategy has tuple of tuple parameters like 

> (Pdb) value
> (('21:00', '2:30'), ('9:00', '11:30'), ('13:00', '15:15'))

, so it still throws error:

>   File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/utils.py", line 29, in paramval2str
>     return value.__name__
> AttributeError: 'tuple' object has no attribute '__name__'

In addition, there are also dictionary parameters, and even empty dictionaries, so I changed line 28 and 29 to:
```python
    elif any(isinstance(value, t) for t in (tuple, dict)):
        # return value.__name__
        return str(value)
```
In this way, it looks the parameters can be correctly converted to strings. But it throws another error:
```python
Traceback (most recent call last):
  File "trend_backtest_eod_mix.py", line 1265, in <module>
    result, analyzers = run_backtest(**test_args)
  File "trend_backtest_eod_mix.py", line 1230, in run_backtest
    cerebro.plot(bok, show=False)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader/cerebro.py", line 996, in plot
    plotter.show()
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 495, in show
    model = self.generate_model(idx)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 296, in generate_model
    meta = Div(text=metadata.get_metadata_div(figurepage.strategy))
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 96, in get_metadata_div
    md += _get_strategy(strategy)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 68, in _get_strategy
    md += f'\n```\n{inspect.getsource(strategy.__class__)}\n```\n\n'
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/Caskroom/miniconda/base/envs/bt/lib/python3.7/inspect.py", line 812, in findsource
    raise OSError('could not find class definition')
OSError: could not find class definition
```
This is because I defined strategy kind of dynamically like:
```python
class TrendBase(bt.Strategy):
    ...

StrategyCls = type(
    'MyTrend', (TrendBase,),
    {'params': MyTrend_params, 'lookup_dict': lookup_dict})
setattr(bt.metabase, StrategyCls.__name__, StrategyCls)
```
So inspect.getsource() cannot find the strategy definition. I just make a simple workaround not returning the definition in metadata.py:
```python
    try:
        md += f'\n```\n{inspect.getsource(strategy.__class__)}\n```\n\n'
    except:
        md += ""
```
then it plots correctly. If there is no way to get the strategy definition in my case, a simple plotting parameter to disable it or even disable the meta tab in the plot html file may help.

I'm sorry for mixing new problems in one issue report, while it's convenient for solving a series. :stuck_out_tongue_winking_eye:

**Comment by verybadsoldier** [comment]
I guess I was a bit too quick regarding the parameter conversion. Please give it another try now using latest commit.

If the strategy code problem is still a thing then please let's move to a dedicated issue and please provide source code reproducing the problem.

**Comment by 0liu** [comment]
Ok, the resampled data plot and params-to-string problems are solved, so I'm closing this issue. I'll try to make test code for the strategy definition problem. Thank you for this great package!
